#!/usr/bin/env bash

_BANG_PATH=$(
  if [ -n "$BANG_SRC_PATH" ]; then
    # If there is a src path stablished, then use it
    echo "$BANG_SRC_PATH"
  else
    # otherwise, lookup for the current directory
    BIN_PATH="$0"
    if [ -L "$BIN_PATH" ]; then
      BIN_PATH=$(readlink "$BIN_PATH")
    fi
    (
      cd $(dirname "$BIN_PATH") > /dev/null
      echo -n "$PWD"
    )
  fi
)

. "$_BANG_PATH/modules/core.sh"
. "$_BANG_PATH/modules/module.sh"
b.module.require 'opt'
b.module.require 'path'
b.module.require 'str'
b.module.require 'task'

b.set bang.src_path "$_BANG_PATH"
b.set bang.working_dir "$PWD"

b.preload "$_BANG_PATH/tasks"

task="$1"

if b.path.executable? "$task"
then
  task="run"
else
  shift
fi

[ -n "$task" ] && b.task.run $task "$@"
